### ISSUE TITLE
improving recordings import

### ISSUE THREAD

**Issue by kdarras** [FrankFundel/BigBAT-GUI#2]
Currently, the WAV files inside my folder "WOB"(that are straight from the Audiomoth) are not shown in the add recordings dialog:
![image](https://github.com/FrankFundel/BigBAT-GUI/assets/7696198/0fdf4515-d617-48ee-a17c-26f5ba5835e1)
But I can import those that are within the subfolders of "WOB" (that were exported from Audacity as signed 16-bit PCM WAV).

However, it would be nice to be able to import multiple recordings simultaneously (with Ctrl-A or Shift + keyboard up/down arrow). Currently, it only works with Shift + mouse click.

Note that you can import the same recording multiple times.

**Comment by FrankFundel** [comment]
My guess would be the extension '.WAV' of your files, because the file-browser filters for '.wav' files. On Windows Ctrl-A works. Thanks for pointing out those problems!

**Comment by kdarras** [comment]
Indeed after renaming the extension of one of the files, the browser finds it - thanks Frank! Would be great to filter for both lowercase and uppercase extensions, then.

**Comment by FrankFundel** [comment]
Thanks! I made the changed accordingly.
